### ISSUE TITLE
FoodCritic crashes on rule FC048

### ISSUE THREAD

**Issue by Chili-Man** [acrmp/foodcritic#278]
It seems to have trouble parsing the following line that is commented in the execute resource block:

```
execute 'dapp-god-restart' do
  user 'root'
  retries 3
  retry_delay 5
  command "god restart #{node['dapp']['name']}"
  only_if { system("god status #{node['dapp']['name']}") } # ~FC048
  action :nothing
end
```

Here's the stack trace I get:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2/lib/gherkin/tag_expression.rb:25:in `eval': (eval):1: syntax error, unexpected tIDENTIFIER, expecting ']' (SyntaxError)
 (vars['{node['dapp']['name']}")'])&&(vars['}'])...
                   ^
(eval):1: syntax error, unexpected tIDENTIFIER, expecting ')'
(vars['{node['dapp']['name']}")'])&&(vars['}'])&&(vars[...
                          ^
(eval):1: syntax error, unexpected ']', expecting ')'
...ars['{node['dapp']['name']}")'])&&(vars['}'])&&(vars['#'])&&...
...                               ^
(eval):1: syntax error, unexpected end-of-input, expecting ')'
...&&(vars['#'])&&(!vars['FC048'])
...                               ^
from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2/lib/gherkin/tag_expression.rb:25:in `evaluate'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/domain.rb:84:in `matches_tags?'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:151:in `ignore_line_match?'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:144:in `block in remove_ignored'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:141:in `reject'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:141:in `remove_ignored'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:80:in `block (2 levels) in check'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:64:in `each'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:64:in `block in check'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:56:in `each'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:56:in `check'
from /opt/chefdk/embedded/apps/foodcritic/lib/foodcritic/linter.rb:26:in `check'
from /opt/chefdk/embedded/apps/foodcritic/bin/foodcritic:5:in `<module:FoodCritic>'
from /opt/chefdk/embedded/apps/foodcritic/bin/foodcritic:3:in `<top (required)>'
from /opt/chefdk/bin/foodcritic:15:in `load'
from /opt/chefdk/bin/foodcritic:15:in `<main>'
```

**Comment by emiller42** [comment]
This isn't specific to the rule.  It appears to blow up if you attempt to put an exclusion on a line which includes # elsewhere in the line.

**Comment by odcinek** [comment]
I did a little digging on this, and I think it's an actual `gherkin` issue.
