### ISSUE TITLE
Crash when running against ntp cookbook version 3.2.0

### ISSUE THREAD

**Issue by mmarschall** [acrmp/foodcritic#496]
I'm running the latest ChefDK:

```
$ chef --version
Chef Development Kit Version: 0.19.6
chef-client version: 12.15.19
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: 1.13.2
```

Running Foodcritic against the mysql cookbook (version 8.0.4), it works as expected:

```
$ foodcritic cookbooks/mysql
FC031: Cookbook without metadata file: cookbooks/mysql/metadata.rb:1
FC045: Metadata does not contain cookbook name: cookbooks/mysql/metadata.rb:1

```
Running Foodcritic against the `ntp` (version 3.2.0) cookbook, it crashes:
```
$ foodcritic cookbooks/ntp/
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:418:in `block_depth': undefined method `size' for nil:NilClass (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:489:in `block (2 levels) in normal_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:489:in `any?'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:489:in `block in normal_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:487:in `normal_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/api.rb:268:in `resource_attributes'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/rules.rb:57:in `block (4 levels) in load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/rules.rb:56:in `map'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/rules.rb:56:in `block (3 levels) in load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:278:in `matches'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:131:in `cookbook_matches'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:102:in `block (2 levels) in check'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:92:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:92:in `block in check'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:83:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:83:in `check'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/lib/foodcritic/linter.rb:28:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/bin/foodcritic:5:in `<module:FoodCritic>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/foodcritic-7.1.0/bin/foodcritic:3:in `<top (required)>'
	from /opt/chefdk/bin/foodcritic:23:in `load'
	from /opt/chefdk/bin/foodcritic:23:in `<main>'

```

**Comment by tas50** [comment]
@mmarschall ChefDK is a bit outdated right now on Foodcritic and I believe this issue might be fixed in the current release. Can you wait until 0.20 ships to see if this magically goes away?

**Comment by tas50** [comment]
I'm fairly certain we fixed this. Closing it out now.
